### ISSUE TITLE
Stuck after "Flushing Cache..."

### ISSUE THREAD

**Issue by aereaux** [cdrdao/cdrdao#10]
Hello, I filed this bug on the sourceforge bugtracker, but it seems like here might be a more appropriate place. I'm having some issues with sdrdao writing a CD. It gets stuck after the "Flushing Cache..." step:
```
$ strace -o strace.log cdrdao write --eject cd.toc
Cdrdao version 1.2.4 - (C) Andreas Mueller <andreas@daneb.de>
/dev/sr0: PLDS DVDRWBD DH-12E3S Rev: MD11
Using driver: Generic SCSI-3/MMC (raw writing) - Version 2.0 (options 0x0000)

Starting write at speed 48...
Pausing 10 seconds - hit CTRL-C to abort.
Process can be aborted with QUIT signal (usually CTRL-\).
Turning BURN-Proof on
Using 96 byte raw P-W sub-channel data mode for CD-TEXT.
Executing power calibration...
Power calibration successful.
WARNING: No super user permission to setup real time scheduling.
Writing lead-in and gap...
Writing track 01 (mode AUDIO/AUDIO )...
Writing track 02 (mode AUDIO/AUDIO )...
Writing track 03 (mode AUDIO/AUDIO )....
Writing track 04 (mode AUDIO/AUDIO )....
Writing track 05 (mode AUDIO/AUDIO )....
Writing track 06 (mode AUDIO/AUDIO )....
Writing track 07 (mode AUDIO/AUDIO )....
Writing track 08 (mode AUDIO/AUDIO )....
Wrote 633 of 633 MB (Buffers 100%  98%).
Wrote 282528 blocks. Buffer fill min 93%/max 100%.
Writing lead-out...
Wrote 15 of 15 MB.
Flushing cache...
```
When I strace it I see this repeated over and over at the end (FD 3 is my drive):
```
ioctl(3, SG_IO, {interface_id='S', dxfer_direction=0 /* SG_DXFER_??? */, cmd_len=6, cmdp="\x00\x00\x00\x00\x00\x00", mx_sb_len=16, iovec_count=0, dxfer_len=0, timeout=30000, flags=SG_FLAG_DIRECT_IO, status=0x2, masked_status=0x1, msg_status=0, sb_len_wr=16, sbp="\x70\x00\x02\x00\x00\x00\x00\x0a\x00\x00\x00\x00\x3a\x01\x00\x00", host_status=0, driver_status=0x8, resid=0, duration=34, info=SG_INFO_CHECK}) = 0
```
Is there something wrong with my CD writer, or is there anything I can tweak to fix this? Let me know if there's any other information I can provide.

**Comment by denisleroy** [comment]
Have you tried without the --eject command ?

**Comment by aereaux** [comment]
Hi, thanks for the response.  I did try without eject, and with `-v 5`.  Here's the output from the last, with the last two lines repeated over and over:

```
Flushing cache...
/dev/sr0: Initiating SCSI command Synchronize Cache
/dev/sr0: SCSI command Synchronize Cache (0x35) executed in 12017 ms, status=0
/dev/sr0: Initiating SCSI command Test Unit Ready
/dev/sr0: SCSI command Test Unit Ready (0x00) executed in 40 ms, status=2
/dev/sr0: Initiating SCSI command Test Unit Ready
```

**Comment by denisleroy** [comment]
status=2 means TEST_UNIT_READY returns a check_condition, which means something went wrong and cdrdao should probe the device to figure out what went wrong, which clearly it's not doing. I'm sorry I can't be more helpful, but this code is so old...

**Comment by aereaux** [comment]
Thanks for taking a look into it at least!  Do you know if there's any other software I can try that can write CD-TEXT?  I tried k3b, but as far as I can tell that part of the writing didn't work.

**Comment by denisleroy** [comment]
cdrecord, theoretically, but it'll take some research effort into its more obscure features. (RIP Jorg Schilling of the legendary flame wars).

**Comment by aereaux** [comment]
Thanks for the advice!  I tweaked my script to output a cue file, and it seems to be working mostly well with cdrecord
