### ISSUE TITLE
Readiness of release 1.2.5

### ISSUE THREAD

**Issue by CrateDepth** [cdrdao/cdrdao#15]
Multiple "tiny" things related to this query which I am raising...

I am interested in gcdmaster.  As per Issue #3 I assume that it is now only compilable with GTK3? (Note: I am aware of at least one or two GTK apps which still need GTK2).  If GTK3 is necessary, then it looks like release 1.2.5 is needed.

How quickly can 1.2.5 be made OPENLY available as a compressed tar file?  This is currently the situation with 1.2.4.

Is there currently stuff left to do before 1.2.5 is released?  If so, what?

Ideally, I would like to have a workable gcdmaster in the next version of Debian Linux 12 (Bookworm).  However, given how cdrdao is "used" in Debian, the deadline is either in 1 to 3 weeks time or the deadline has been missed.

Sorry for the vagueness of the query which I am raising.  I have only really just started learning about the Debian package creation process together with Debian's strict deadlines.  Therefore, the questions I have or will ask may have a lot of flex in them.

**Comment by denisleroy** [comment]
Hi there,

The current dev branch is I believe pretty much ready for 1.2.5. If you have a chance to test it out, I'd appreciate any feedback.

There is a "basic" gtk3 port merged in (port by steffanroellin), although it keeps the visual aspect of gcdmaster similar to the  old gtk2 version. There is a gtk3 branch that I worked on at some point, which is a more inline with the GTK-3 ways of things, but it's not entirely complete, and I don't have time to finish it at this point.

Some of the possible missing things that I had in mind to release dev as 1.2.5 was the UTF-8 toc support added in 1.2.5 which I think required some tweaks in toc2mp3, but this is pretty minor and doesn't break things by default.

**Comment by alex-free** [comment]
> Summarising what you wrote above, it looks like there are two things:
> 
>     1. UTF-8: You want to quickly add in UTF-8 toc support to 1.2.5.  I assume that would just take one evening.  I don't know which evening you'll do that on :-)
> 
>     2. Testing: You want testing done independent of @steffanroellin.  I have a relatively old build environment and I don't know whether it is suitable for compiling cdrdao/gcdmaster.  Having said that, I am running a GTK3 GUI right now.
> 
> 
> Therefore, you want both of the above to be done before release 1.2.5 goes out?

I hope this bug fix gets in 1.2.5.
https://github.com/cdrdao/cdrdao/pull/14

**Comment by denisleroy** [comment]
The UTF-8 support is already in dev and reasonably well tested. I have some french CDs with diacritics in track names and those are now handled correctly. It was more complicated than that, the CD-R format has some support for it which wasn't handled correctly by the TOC format.

I'm sorry I didn't have time to look at #14, I'll do that within the next few days.
