### ISSUE TITLE
cdrdao (1.2.4-1) breaks dependency

### ISSUE THREAD

**Issue by johnpiers** [cdrdao/cdrdao#2]
Arch Linux 64 Bit installation:
"installing cdrdao (1.2.4-1) breaks dependency 'cdrdao=1.2.3' required by gcdmaster"

Apologies if this is in the wrong place, just wondering if it's the update or Arch itself that's causing the problem.

**Comment by denisleroy** [comment]
Hi. Looks like an arch-specific packaging issue, you may want to talk to the Arch packager. gcdmaster is part of cdrdao, and both are built together. You may want to uninstall gcdmaster to fix this.

**Comment by johnpiers** [comment]
Thank you.
